# -*- coding: utf-8 -*-
"""f1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_6MLDuxYBXZJTU_-bNr-tgsOxnvHSbAj
"""

# ---------------------------------------------------------
# 1️⃣ ایمپورت کتابخانه‌ها
# ---------------------------------------------------------
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# ---------------------------------------------------------
# 2️⃣ دانلود دیتاست CIFAR-100
# ---------------------------------------------------------
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar100.load_data(label_mode='fine')

print(f"Train shape: {x_train.shape}")
print(f"Test shape: {x_test.shape}")

# ---------------------------------------------------------
# 3️⃣ تعریف کلاس‌های people
# ---------------------------------------------------------
people_classes = ['baby', 'boy', 'girl', 'man', 'woman']
people_class_indices = [2, 11, 35, 40, 98]  # اندیس کلاس‌های people در CIFAR-100

# ---------------------------------------------------------
# 4️⃣ فیلتر کردن داده‌ها
# ---------------------------------------------------------
# فیلتر داده‌های آموزشی
train_filter = np.isin(y_train, people_class_indices).flatten()
x_train_people = x_train[train_filter]
y_train_people = y_train[train_filter]

# فیلتر داده‌های تست
test_filter = np.isin(y_test, people_class_indices).flatten()
x_test_people = x_test[test_filter]
y_test_people = y_test[test_filter]

# نگاشت اندیس‌های کلاس به ۰ تا ۴
class_mapping = {original: new for new, original in enumerate(people_class_indices)}
y_train_mapped = np.array([class_mapping[label[0]] for label in y_train_people])
y_test_mapped = np.array([class_mapping[label[0]] for label in y_test_people])

# نرمال‌سازی تصاویر
x_train_people = x_train_people.astype('float32') / 255.0
x_test_people = x_test_people.astype('float32') / 255.0

# تبدیل برچسب‌ها به one-hot encoding
y_train_categorical = keras.utils.to_categorical(y_train_mapped, num_classes=5)
y_test_categorical = keras.utils.to_categorical(y_test_mapped, num_classes=5)

print(f"Train data shape: {x_train_people.shape}, Labels shape: {y_train_categorical.shape}")
print(f"Test data shape: {x_test_people.shape}, Labels shape: {y_test_categorical.shape}")

# ---------------------------------------------------------
# 5️⃣ نمایش چند تصویر
# ---------------------------------------------------------
plt.figure(figsize=(12,6))
for i in range(10):
    plt.subplot(2,5,i+1)
    plt.imshow(x_train_people[i])
    plt.title(people_classes[y_train_mapped[i]])
    plt.axis('off')
plt.tight_layout()
plt.show()

# ---------------------------------------------------------
# 6️⃣ ساخت مدل MLP
# ---------------------------------------------------------
model = models.Sequential([
    layers.Flatten(input_shape=(32,32,3)),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(5, activation='softmax')  # ۵ کلاس people
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# ---------------------------------------------------------
# 7️⃣ آموزش مدل
# ---------------------------------------------------------
history = model.fit(
    x_train_people, y_train_categorical,
    validation_data=(x_test_people, y_test_categorical),
    epochs=15,
    batch_size=64
)

# ---------------------------------------------------------
# 8️⃣ رسم نمودار دقت و خطا
# ---------------------------------------------------------
plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

# ---------------------------------------------------------
# 9️⃣ ارزیابی مدل
# ---------------------------------------------------------
loss, accuracy = model.evaluate(x_test_people, y_test_categorical)
print(f'Loss: {loss:.4f}, Accuracy: {accuracy:.4f}')

# ---------------------------------------------------------
# 🔟 Confusion Matrix
# ---------------------------------------------------------
y_pred_probs = model.predict(x_test_people)
y_pred_classes = np.argmax(y_pred_probs, axis=1)
y_true_classes = np.argmax(y_test_categorical, axis=1)

cm = confusion_matrix(y_true_classes, y_pred_classes)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=people_classes)
disp.plot(cmap='Blues')
plt.show()

