# -*- coding: utf-8 -*-
"""f2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tLjrLlDc575A_WgjT2kyZLjfXY64FQ4G
"""

from google.colab import files

uploaded = files.upload()

# ----------------------------------------------------------
# 1. ایمپورت کتابخانه‌ها
# ----------------------------------------------------------
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import zipfile

# ----------------------------------------------------------
# 2. استخراج فایل zip دیتاست
# ----------------------------------------------------------
zip_path = '/content/dta.zip'        # اسم فایل zip
extract_path = '/content/dta'        # مسیر استخراج

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# ----------------------------------------------------------
# 3. تعریف ImageDataGenerator با Augmentation
# ----------------------------------------------------------
datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=30,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=0.2,
    brightness_range=[0.8,1.2]
)

train_generator = datagen.flow_from_directory(
    extract_path,
    target_size=(64, 64),
    batch_size=32,
    class_mode='categorical',
    subset='training',
    shuffle=True
)

val_generator = datagen.flow_from_directory(
    extract_path,
    target_size=(64, 64),
    batch_size=32,
    class_mode='categorical',
    subset='validation',
    shuffle=False
)

# ----------------------------------------------------------
# 4. نمایش تعدادی تصویر
# ----------------------------------------------------------
class_names = list(train_generator.class_indices.keys())
plt.figure(figsize=(12,6))
for images, labels in train_generator:
    for i in range(10):
        plt.subplot(2,5,i+1)
        plt.imshow(images[i])
        plt.title(f"{class_names[np.argmax(labels[i])]}")
        plt.axis('off')
    break
plt.show()

# ----------------------------------------------------------
# 5. ساخت مدل CNN
# ----------------------------------------------------------
model = keras.Sequential([  # این خط یک مدل Sequential می‌سازه که لایه‌ها رو به ترتیب اضافه می‌کنیم.
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(64,64,3)), # این لایه ویژگی‌های اولیه تصویر رو یاد می‌گیره.
    layers.MaxPooling2D(pool_size=(2,2)), #این لایه اندازه تصویر رو نصف می‌کنه
    layers.Conv2D(64, (3,3), activation='relu'), #می‌تونه ویژگی‌های پیچیده‌تری مثل گوشه‌ها و الگوهای ترکیبی رو یاد بگیره.
    layers.MaxPooling2D(pool_size=(2,2)), #مثل قبل، اندازه رو نصف می‌کنه
    layers.Conv2D(128, (3,3), activation='relu'), #ویژگی‌های خیلی پیچیده‌تر (مثل اشکال خاص و الگوهای ترکیبی) رو یاد می‌گیره
    layers.MaxPooling2D(pool_size=(2,2)), # اندازه تصویر رو دوباره نصف می‌کنه.
    layers.Flatten(), # آرایه ۳بعدی خروجی رو به یک آرایه ۱بعدی تبدیل می‌کنه
    layers.Dense(256, activation='relu'), #این بخش تصمیم‌گیری مدل رو انجام میده.
    layers.Dropout(0.3), #برای جلوگیری از overfitting مدل رو مجبور می‌کنه وابسته به تعداد کمی از نورون‌ها نباشه
    layers.Dense(train_generator.num_classes, activation='softmax') # لایه خروجی
])

# ----------------------------------------------------------
# 6. کامپایل مدل
# ----------------------------------------------------------
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# ----------------------------------------------------------
# 7. آموزش مدل
# ----------------------------------------------------------
history = model.fit(
    train_generator,
    epochs=15,
    validation_data=val_generator
)

# ----------------------------------------------------------
# 8. رسم نمودار دقت و خطا
# ----------------------------------------------------------
plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.show()

# ----------------------------------------------------------
# 9. Confusion Matrix
# ----------------------------------------------------------
val_generator.reset()
y_pred = model.predict(val_generator)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = val_generator.classes

cm = confusion_matrix(y_true, y_pred_classes)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
disp.plot(cmap='Blues')
plt.show()